# Acknoledgements {-}

The following pages represent the fulfillment of my aerospace engineering studies. It is for this reason that firstly I would like to show my gratitude to all those who have been by my side during this journey, who have encouraged and believed in me. 

Elaborating this project has represented a challenge since the very beginning. Coronavirus has forced me to leave a previous study unfinished. Even though, and thanks to my supervisors Oriol Lordan and Jose Maria Sallan, I have overcome the situation elaborating what I consider to be a fascinating project. I would like to express my appreciation to them not only for its readiness to help but, to advice and support me in a totally unexpected situation.

The completion of this project would not have been possible without the contirbution of Carlota, Pol and Cristina. They made an enormous effort elaborating with me the required database in record time. I would like to express my sincere gratitude for their help. Their genoristy has totally overwhelmed me.

I want to give a special mention to my best friend and partner Quit, her positivism and company has allowed me to face this project with enthusiasm and determination.

Finally, a big thanks to my parents for their unconditional support, help and love. I owe my success to them. 